dist: trusty
sudo: true
  #
language: c
  #
notifications:
  email: true
  #
before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
  #
  # Start fb X server
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  #
install:
  #
  # Install arduino 1.6.10
  - wget http://downloads-02.arduino.cc/arduino-1.6.10-linux64.tar.xz
  - tar xf arduino-1.6.10-linux64.tar.xz
  - sudo mv arduino-1.6.10 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino ${TRAVIS_BUILD_DIR}/buildroot/bin/arduino
  #
before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  - ls
  #
script:
  #
  # Backup Configuration.h, and pins_UNO_1.h
  #
  - cp EACU/Configuration.h EACU/Configuration.h.backup
  #
  # Build with the default configurations
  #
  - build_eacu
  #
  # reset config
  - restore_configs
  # test with electric motor. at the moment does nothing
  - opt_set MOTOR 2
  - build_eacu
  # reset config
  - restore_configs
  # test with no smart running
  - opt_disable EXHAUST_OX
  - opt_disable CHOKE
  - build_eacu
  # reset config
  - restore_configs
  # test with choke but no o3 sensor
  - opt_disable EXHAUST_OX
  - opt_enable
  - build_eacu
