dist: trusty
sudo: true
  #
language: c
  #
notifications:
  email: true
  #
before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}
  #
  # Start fb X server
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  #
install:
  #
  # Install arduino 1.6.10
  - wget http://downloads-02.arduino.cc/arduino-1.6.10-linux64.tar.xz
  - tar xf arduino-1.6.10-linux64.tar.xz
  - sudo mv arduino-1.6.10 /usr/local/share/arduino
  - ln -s /usr/local/share/arduino/arduino ${TRAVIS_BUILD_DIR}/buildroot/bin/arduino
  #
before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  - generate_version_header_for_marlin ${TRAVIS_BUILD_DIR}/Marlin
  - cat ${TRAVIS_BUILD_DIR}/Marlin/_Version.h
  #
script:
  #
  # Backup Configuration.h, and pins_UNO_1.h
  #
  - cp EACU/Configuration.h EACU/Configuration.h.backup
  - cp EACU/pins_UNO_1.h EACU/pins_UNO_1.h.backup
  #
  # Build with the default configurations
  #
  - build_marlin
  #
  # Test 2 extruders (one MAX6675) and heated bed on basic RAMPS 1.4
  # Test a "Fix Mounted" Probe with Safe Homing, some arc options,
  # linear bed leveling, M48, leveling debug, and firmware retraction.
  #
  - opt_set MOTHERBOARD BOARD_RAMPS_14_EEB
  - opt_set EXTRUDERS 2
  - opt_set TEMP_SENSOR_0 -2
  - opt_set TEMP_SENSOR_1 1
  - opt_set TEMP_SENSOR_BED 1
  - opt_enable PIDTEMPBED FIX_MOUNTED_PROBE Z_SAFE_HOMING ARC_P_CIRCLES CNC_WORKSPACE_PLANES CNC_COORDINATE_SYSTEMS
  - opt_enable REPRAP_DISCOUNT_SMART_CONTROLLER SDSUPPORT EEPROM_SETTINGS
  - opt_enable BLINKM PCA9632 RGB_LED NEOPIXEL_LED
  - opt_enable AUTO_BED_LEVELING_LINEAR Z_MIN_PROBE_REPEATABILITY_TEST DEBUG_LEVELING_FEATURE SKEW_CORRECTION SKEW_CORRECTION_FOR_Z SKEW_CORRECTION_GCODE
  - opt_enable_adv FWRETRACT MAX7219_DEBUG LED_CONTROL_MENU
  - opt_set ABL_GRID_POINTS_X 16
  - opt_set ABL_GRID_POINTS_Y 16
  - opt_set_adv FANMUX0_PIN 53
  - build_marlin
  #
